_commit: 0.0.2rc-140-gfb19b08
_src_path: gh:bswck/skeleton
author: bswck
cli: false
copyright: Bartosz Sławecki
description: Get the caller expression.
docs: true
email: bswck.dev@gmail.com
github: bswck
license: MIT
package: backframe
precommit: true
pypi: true
pypi_description: Get the caller expression.
pypi_project: backframe
pypy: true
python: '3.8'
python_max: '4.0'
repo: backframe
rtd: backframe
tests: true
visibility: public
wip: false
