_commit: 0.0.2rc-215-g792492f
_src_path: gh:bswck/skeleton
author: bswck
cli: false
copyright: Bartosz Sławecki
description: Inspect the caller.
docs: true
email: bswck.dev@gmail.com
github: bswck
license: MIT
package: backframe
precommit: true
pypi: true
pypi_description: Inspect the caller.
pypi_project: backframe
pypy: true
python: '3.8'
python_until: '4.0'
repo: backframe
rtd: backframe
tests: true
tidelift: false
visibility: public
wip: false
